#!/bin/bash

rm -rf tds

mkdir -p tds/doc/generic/thumbpdf
mkdir -p tds/scripts/thumbpdf
mkdir -p tds/tex/generic/thumbpdf

cp README.md tds/doc/generic/thumbpdf/README
cp thumbpdf.pl tds/scripts/thumbpdf
cp thumbpdf.sty thumbpdf.tex tds/tex/generic/thumbpdf

cd tds
zip -r thumbpdf.tds.zip doc scripts tex
mv thumbpdf.tds.zip ..

cd ..

rm -r tds

zip thumbpdf.zip thumbpdf.{tex,sty,pl} README.md thumbpdf.tds.zip
