#!/bin/bash

rm -rf tds

mkdir -p tds/doc/generic/thumbpdf
mkdir -p tds/scripts/thumbpdf
mkdir -p tds/tex/generic/thumbpdf

cp README.md tds/doc/generic/thumbpdf/README
cp thumbpdf.pl tds/scripts/thumbpdf
cp thumbpdf.sty thumbpdf.tex tds/tex/generic/thumbpdf

cd tds
zip -r thumbpdf.tds.zip doc scripts tex
mv thumbpdf.tds.zip ../..

cd ..
rm -r tds

cd ..


rm -f thumbpdf.zip
zip thumbpdf.zip thumbpdf/thumbpdf.{tex,sty,pl} thumbpdf/README.md thumbpdf.tds.zip

mv thumbpdf.zip thumbpdf.tds.zip thumbpdf

